version: "3.9"
   
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/opt/second-city/code
    ports:
      - "8000:8000"

